export const data = {
  version: '3.6.3',
  objects: [
    {
      angle: 0,
      backgroundColor: "",
      clipTo: null,
      fill: "transparent",
      fillRule: "nonzero",
      flipX: false,
      flipY: false,
      globalCompositeOperation: "source-over",
      height: 185.9,
      left: 11.92,
      opacity: 1,
      originX: "left",
      originY: "top",
      paintFirst: "fill",
      rx: 0,
      ry: 0,
      scaleX: 1,
      scaleY: 1,
      shadow: null,
      skewX: 0,
      skewY: 0,
      stroke: "#000000",
      strokeDashArray: null,
      strokeDashOffset: 0,
      strokeLineCap: "butt",
      strokeLineJoin: "miter",
      strokeMiterLimit: 4,
      strokeWidth: 1,
      top: 14.99,
      transformMatrix: null,
      type: "rect",
      version: "3.6.3",
      visible: true,
      width: 278,
    },
    {
      angle: 0,
      backgroundColor: "",
      clipTo: null,
      fill: "transparent",
      fillRule: "nonzero",
      flipX: false,
      flipY: false,
      globalCompositeOperation: "source-over",
      height: 194.89,
      left: 1083.92,
      opacity: 1,
      originX: "left",
      originY: "top",
      paintFirst: "fill",
      rx: 0,
      ry: 0,
      scaleX: 1,
      scaleY: 1,
      shadow: null,
      skewX: 0,
      skewY: 0,
      stroke: "#000000",
      strokeDashArray: null,
      strokeDashOffset: 0,
      strokeLineCap: "butt",
      strokeLineJoin: "miter",
      strokeMiterLimit: 4,
      strokeWidth: 1,
      top: 1080.41,
      transformMatrix: null,
      type: "rect",
      version: "3.6.3",
      visible: true,
      width: 191,
    },
  ],
  version: "3.6.3",
}
