export const data = {
  objects: [
    {
      type: 'rect',
      version: '3.6.3',
      originX: 'left',
      originY: 'top',
      left: 12.5,
      top: 22.98,
      width: 237,
      height: 113.92,
      fill: 'transparent',
      stroke: '#000000',
      strokeWidth: 1,
      strokeDashArray: null,
      strokeLineCap: 'butt',
      strokeDashOffset: 0,
      strokeLineJoin: 'miter',
      strokeMiterLimit: 4,
      scaleX: 1,
      scaleY: 1,
      angle: 0,
      flipX: false,
      flipY: false,
      opacity: 1,
      shadow: null,
      visible: true,
      clipTo: null,
      backgroundColor: '',
      fillRule: 'nonzero',
      paintFirst: 'fill',
      globalCompositeOperation: 'source-over',
      transformMatrix: null,
      skewX: 0,
      skewY: 0,
      rx: 0,
      ry: 0,
    },
    {
      type: 'rect',
      version: '3.6.3',
      originX: 'left',
      originY: 'top',
      left: 1012.5,
      top: 1039.24,
      width: 126,
      height: 101.93,
      fill: 'transparent',
      stroke: '#000000',
      strokeWidth: 1,
      strokeDashArray: null,
      strokeLineCap: 'butt',
      strokeDashOffset: 0,
      strokeLineJoin: 'miter',
      strokeMiterLimit: 4,
      scaleX: 1,
      scaleY: 1,
      angle: 0,
      flipX: false,
      flipY: false,
      opacity: 1,
      shadow: null,
      visible: true,
      clipTo: null,
      backgroundColor: '',
      fillRule: 'nonzero',
      paintFirst: 'fill',
      globalCompositeOperation: 'source-over',
      transformMatrix: null,
      skewX: 0,
      skewY: 0,
      rx: 0,
      ry: 0,
    },
  ],
}
