export const data = {
  version: '3.6.3',
  objects: [
    {
      type: 'rect',
      version: '3.6.3',
      originX: 'left',
      originY: 'top',
      left: 50.5,
      top: 22.98,
      width: 91,
      height: 80.94,
      fill: 'transparent',
      stroke: '#000000',
      strokeWidth: 1,
      strokeDashArray: null,
      strokeLineCap: 'butt',
      strokeDashOffset: 0,
      strokeLineJoin: 'miter',
      strokeMiterLimit: 4,
      scaleX: 1,
      scaleY: 1,
      angle: 0,
      flipX: false,
      flipY: false,
      opacity: 1,
      shadow: null,
      visible: true,
      clipTo: null,
      backgroundColor: '',
      fillRule: 'nonzero',
      paintFirst: 'fill',
      globalCompositeOperation: 'source-over',
      transformMatrix: null,
      skewX: 0,
      skewY: 0,
      rx: 0,
      ry: 0,
    },
  ],
  background: {
    type: 'pattern',
    source: 'http://localhost:9001/static/images/cell.ea733ac4b4347ad7d6c013adfeea12dc.png',
    repeat: 'repeat',
    crossOrigin: '',
    offsetX: 0,
    offsetY: 0,
    patternTransform: null,
  },
}
